INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Feed Me", "Hunger", 500, "2018-01-14", "2018-01-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Filming", "Movie", 20000, "2018-02-01", "2018-03-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Gym", "Exercise", 2000, "2018-01-15", "2018-02-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Clothes", "Clothes", 1000, "2018-01-14", "2018-02-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Need Textbooks", "Books", 500, "2018-01-15", "2018-02-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Vacation", "Travel", 2500, "2018-02-01", "2018-04-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("In Debt", "Debt", 50000, "2018-01-14", "2018-12-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Uniform", "Clothes", 100, "2018-01-15", "2018-02-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Car", "Transportation", 5000, "2018-02-01", "2018-03-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rent Money", "Rent", 1200, "2018-01-14", "2018-01-31");

INSERT INTO users (name, age) VALUES ("Charles", 42);
INSERT INTO users (name, age) VALUES ("Matt", 27);
INSERT INTO users (name, age) VALUES ("Rachel", 26);
INSERT INTO users (name, age) VALUES ("Fry", 6);
INSERT INTO users (name, age) VALUES ("Adrian", 30);
INSERT INTO users (name, age) VALUES ("Justin", 27);
INSERT INTO users (name, age) VALUES ("Maria", 32);
INSERT INTO users (name, age) VALUES ("Sheena", 24);
INSERT INTO users (name, age) VALUES ("Andria", 23);
INSERT INTO users (name, age) VALUES ("Courtney", 24);
INSERT INTO users (name, age) VALUES ("Lisa", 24);
INSERT INTO users (name, age) VALUES ("Simon", 24);
INSERT INTO users (name, age) VALUES ("Dina", 50);
INSERT INTO users (name, age) VALUES ("Mike", 49);
INSERT INTO users (name, age) VALUES ("Jonathan", 51);
INSERT INTO users (name, age) VALUES ("Shawn", 27);
INSERT INTO users (name, age) VALUES ("JP", 32);
INSERT INTO users (name, age) VALUES ("Steve", 42);
INSERT INTO users (name, age) VALUES ("Norman", 56);
INSERT INTO users (name, age) VALUES ("Eli", 25);

INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 1, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1200, 10, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 7, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400, 9, 8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (888, 6, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (43, 8, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (12, 2, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (18, 3, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (14, 5, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (23, 4, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (8, 8, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 3, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (18, 5, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (22, 6, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (4, 4, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (22, 5, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (56, 9, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (19, 2, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (33, 1, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (21, 6, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (30, 4, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2, 2, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (18, 3, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 5, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (9, 9, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (18, 3, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (21, 4, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1, 2, 3);
